version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: experimentdb
      POSTGRES_USER: experimentuser
      POSTGRES_PASSWORD: experimentpass
    ports:
      - "5432:5432"
#    healthcheck:
#      test: ["CMD", "pg_isready", "-U", "experimentuser"]
#      interval: 5s
#      timeout: 5s
#      retries: 5


#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin_container
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@example.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#    ports:
#      - "5050:80"
#    depends_on:
#      - db
  app:
#    image: k1moo/themeexperiment-app
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: experimentdb
      DB_USER: experimentuser
      DB_PASSWORD: experimentpass
    ports:
      - "8080:8080"
