
spring:
  application:
    name: themeExperiment
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:experimentdb}
#    url: jdbc:postgresql://${DB_HOST:176.99.130.184}:${DB_PORT:5432}/${DB_NAME:experimentdb}
    username: ${DB_USER:experimentuser}
    password: ${DB_PASSWORD:experimentpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true


  # Logging level for Thymeleaf
logging:
  level:
    org:
      thymeleaf=DEBUG:
server:
  port: 8080
